# Generated by Django 3.0.7 on 2020-06-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0002_auto_20200625_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'Priorities'},
        ),
    ]
