# Generated by Django 3.0.7 on 2020-06-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0003_auto_20200625_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='favorites',
            field=models.CharField(choices=[(True, 'True'), (False, 'False')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='favorites',
            field=models.CharField(choices=[(True, 'True'), (False, 'False')], default=False, max_length=20),
        ),
    ]
