# Generated by Django 3.0.7 on 2020-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0004_auto_20200625_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='favorites',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='favorites',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
    ]
