# Generated by Django 3.0.7 on 2020-06-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0007_labelcolor_prioritycolor_projectcolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityColor',
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='taskker.LabelColor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='taskker.ProjectColor'),
        ),
    ]
