# Generated by Django 3.0.7 on 2020-06-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0008_auto_20200630_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taskker.LabelColor'),
        ),
    ]
