# Generated by Django 3.0.7 on 2020-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0010_auto_20200703_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('p1', 'danger-dark'), ('p2', 'warning-dark'), ('p3', 'info-dark'), ('no priority', 'black')], max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(choices=[('p1', 'danger-dark'), ('p2', 'warning-dark'), ('p3', 'info-dark'), ('no priority', 'black')], default='no priority', max_length=20),
        ),
    ]
