# Generated by Django 3.0.7 on 2020-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0011_auto_20200703_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('danger-dark', 'p1'), ('warning-dark', 'p2'), ('info-dark', 'p3'), ('black', 'no priority')], max_length=255),
        ),
    ]
