# Generated by Django 3.0.7 on 2020-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0012_auto_20200703_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(choices=[('danger-dark', 'p1'), ('warning-dark', 'p2'), ('info-dark', 'p3'), ('black', 'no priority')], default='no priority', max_length=20),
        ),
    ]
