# Generated by Django 3.0.7 on 2020-07-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskker', '0017_auto_20200703_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(blank=True, default='no priority', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='taskker.Priority'),
        ),
    ]
